# 외부 API 임시 기본 주소
external.api01.base-url=https://apis.data.go.kr/B552845/recent

# 외부 API 임시 인증키
external.api01.api-key=${API01_KEY}

# 현재 단계에서는 DB 연결 설정을 팀원이 나중에 직접 추가합니다.
# 그전까지 Spring Boot가 시작하면서 DataSource와 JPA 연결을 자동 시도하지 않게 합니다.
# spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
